# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  master_ip = nil

  # Master configuration
  config.vm.define "saltmaster" do |master|
    master.vm.box = "ubuntu/bionic64"
    master.vm.network "private_network", type: "dhcp"
    master.vm.hostname = "saltmaster.local"
    # Provisioning for Salt Master
    master.vm.provision "shell", inline: <<-SHELL
      MASTER_IP=$(ip addr show | grep 'inet ' | grep '192.168.' | awk '{print $2}' | cut -d'/' -f1)
      echo $MASTER_IP > /vagrant/master_ip.txt
    SHELL
    master.vm.provision "shell", path: "setup_salt_master.sh"
  end

  # Minion configuration
  config.vm.define "saltminion1" do |minion1|
    minion1.vm.box = "ubuntu/bionic64"
    minion1.vm.network "private_network", type: "dhcp"
    minion1.vm.hostname = "saltminion1.local"
    minion1.vm.network "forwarded_port", guest: 80, host: 8080
    minion1.vm.provision "shell", inline: <<-SHELL
      MASTER_IP=$(cat /vagrant/master_ip.txt)
      /vagrant/setup_salt_minion.sh "$MASTER_IP"
    SHELL
  end
  
  # ... add more minions or other VM configurations as needed ...

end
